### ISSUE TITLE
After clicking the app icon nothing happens

### ISSUE THREAD

**Issue by Wiggins2610** [julien-nc/integration_collaboard#1]
Hi @julien-nc, 
i connected my account to the collaboard servers. First time I received an error "login/password incorrect", which isnt the case. 
Trying a 2nd time it seems to work then. 
But after launching the app by clicking the Icon, nothing happens. Only a empty nextcloud page.
How can I fix it?

**Comment by julien-nc** [comment]
Could you check the browser console logs? You could also look for lines related with `integration_collaboard` in nextcloud.log.

**Comment by Wiggins2610** [comment]
What kind of information do you need? I hope I provide the right lines....

**Browser Log, what looks to me as errors:** 

ypeError: this.state.project_list.filter is not a function
    at o.activeProjects (App.vue:151:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.activeProjects (vue.runtime.esm.js:5537:25)
    at o.activeProjectCount (App.vue:168:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.activeProjectCount (vue.runtime.esm.js:5537:25)
    at o.<anonymous> (App.vue?3dfd:1:800)
    at e._render (vue.runtime.esm.js:2684:28)


**I copied out from nextcloud.log ....**   

"2023-03-29T13:46:53+00:00","remoteAddr":"xx.xx.x.x","user":"username","app":"integration_collaboard","method":"GET","url":"/apps/integration_collaboard/","message":"Collaboard API client error : Client error: `POST https://api.collaboard.app/api/CollaborationHub/GetParticipatingProjecs` resulted in a `404 Not Found` response","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","version":"26.0.0.11","data":{"app":"integration_collaboard","responseBody":"null","exception":"Client error: `POST https://api.collaboard.app/api/CollaborationHub/GetParticipatingProjecs` resulted in a `404 Not Found` response"}}
{"reqId":"Sg80jWh8oKqYKeUAZmq0","level":2,"time":"

**Comment by Wiggins2610** [comment]
Any news on that @julien-nc?

**Comment by dinosmm** [comment]
I too see an empty Nextcloud page (i.e. my background and top apps bar, but no app loaded, when I click on the Collaboard app. I am connected to my Collaboard account successfully in settings.

Here is my browser console error:

TypeError: this.state.project_list.filter is not a function
    activeProjects App.vue:151
    VueJS 3
    activeProjectCount App.vue:167
    VueJS 3
    IA App.vue:1
    VueJS 6
    <anonymous> main.js:13
[vue.runtime.esm.js:3049:8](webpack:///integration_collaboard/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 9
    <anonymous> main.js:13

​

**Comment by Wiggins2610** [comment]
Still not working @julien-nc 

Failed to get the project list
Collaboard API client error
