### ISSUE TITLE
Chang wrong password

### ISSUE THREAD

**Issue by thomaskor** [julien-nc/integration_collaboard#14]
Hi,
Who can I change an password in Nextcloud. I have an wrong password inside.
Thanks.

**Comment by thomaskor** [comment]
I've found it. But I have the error message:  "Failed to get the project list 
Collaboard API client error".
In settings, Collaboard is connected.

**Comment by Wiggins2610** [comment]
> I've found it. But I have the error message: "Failed to get the project list Collaboard API client error". In settings, Collaboard is connected.

Same here. Any ideas how to fix that?
I already postet this issue, that was closed without solving it.

**Comment by jhergeth** [comment]
Same here ..................
In "Connected accounts" I have a "Connected as ..."

I am trying to use a free collaboard account.

**Comment by thomaskor** [comment]
Hi together,

a short feedback.
After update it works.

**Comment by thomaskor** [comment]
Thank you very much.
